// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpEcV0QwbApqQD1TX-eV3aKYw9adk74y8',
    appId: '1:200497592401:web:b29095300aa6d9629ae070',
    messagingSenderId: '200497592401',
    projectId: 'socialapp-d1f34',
    authDomain: 'socialapp-d1f34.firebaseapp.com',
    storageBucket: 'socialapp-d1f34.appspot.com',
    measurementId: 'G-HGKLWN1NCJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqiPbGCP_tMV0FIWNx6-EzTeD68EVGrwY',
    appId: '1:200497592401:android:210fd9ed8400ad329ae070',
    messagingSenderId: '200497592401',
    projectId: 'socialapp-d1f34',
    storageBucket: 'socialapp-d1f34.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfRkHOPTyypXUzLVNnT7qpHBY6GitidVk',
    appId: '1:200497592401:ios:34e70e0ecf86689f9ae070',
    messagingSenderId: '200497592401',
    projectId: 'socialapp-d1f34',
    storageBucket: 'socialapp-d1f34.appspot.com',
    iosBundleId: 'com.example.ecommerceproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfRkHOPTyypXUzLVNnT7qpHBY6GitidVk',
    appId: '1:200497592401:ios:34e70e0ecf86689f9ae070',
    messagingSenderId: '200497592401',
    projectId: 'socialapp-d1f34',
    storageBucket: 'socialapp-d1f34.appspot.com',
    iosBundleId: 'com.example.ecommerceproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpEcV0QwbApqQD1TX-eV3aKYw9adk74y8',
    appId: '1:200497592401:web:9fc22d503d69c4f69ae070',
    messagingSenderId: '200497592401',
    projectId: 'socialapp-d1f34',
    authDomain: 'socialapp-d1f34.firebaseapp.com',
    storageBucket: 'socialapp-d1f34.appspot.com',
    measurementId: 'G-65X20H463P',
  );

}